apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-app
  namespace: argocd
spec:
  destination:
    namespace: helloworld-ns
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  source:
    path: helloworld
    repoURL: 'https://src.scub.net/valentin.viovi/service-test.git'
    targetRevision: main 
    helm:
      valueFiles:
        - values.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: helloworld
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: 'https://src.scub.net/valentin.viovi/service-test.git'
  username: "gitlab+deploy-token-34"
  password: "3Lm7ZKYrTTTK94zvw_mB"

