apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  source:
    path: argocd/applications
    repoURL: 'https://src.scub.net/valentin.viovi/argocd-test.git'
    targetRevision: main
    directory:
      recurse: true
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: 'https://src.scub.net/valentin.viovi/argocd-test.git'
  username: "gitlab+deploy-token-35"
  password: "g6gxV6AaocsHj_L5U4GX"
