apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-app
  namespace: argocd
spec:
  destination:
    namespace: helloworld-ns
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  source:
    path: apps/helloworld
    repoURL: 'https://src.scub.net/valentin.viovi/argocd-test.git'
    targetRevision: main 
    helm:
      valueFiles:
        - values.yaml


